kind: pipeline
type: docker
name: 2DoListPipeline

trigger:
  event:
    - push

steps:
- name: web-server
  image: plugins/docker
  settings:
    dockerfile: ./Dockerfile
    context: sources/
    registry: hub.codefirst.iut.uca.fr
    repo: hub.codefirst.iut.uca.fr/felix.mielcarek/2_do_list
    username:
      from_secret: secret-registry-username
    password:
      from_secret: secret-registry-password
      
- name: deploy-container
  image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
  environment:
    IMAGENAME: hub.codefirst.iut.uca.fr/felix.mielcarek/2_do_list:latest
    CONTAINERNAME: 2_do_list
    COMMAND: create
    OVERWRITE: true
  depends_on: [ web-server ]